name: Delayed Queue
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test and generate coverage report
      run: |
        go test `go list ./... | grep -v examples` -coverprofile=cover.out -covermode=atomic
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        files: ./cover.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)